package Engine;

import java.util.ArrayList;
import java.util.List;

import Parser.Node;
import Parser.Parser;
import Standardizer.AST;
import Standardizer.BuildAST;
import Lexical_Analyser.LexicalAnalyser;
import Lexical_Analyser.Token;

public class Evaluvator {
    public static String evaluvate(String filename, boolean isPrintAST, boolean isPrintST){

	      LexicalAnalyser scanner = new LexicalAnalyser(filename);
	      List<Token> tokens;
	      List<Node> AST;   
			try {
				tokens = scanner.scan();
				if(tokens.isEmpty()){
					System.out.println("Empty PROGRAM!!!!!!!!");
					return "";
				}
				Parser parser = new Parser(tokens);
				AST=parser.parse();
				
				ArrayList<String> stringAST = parser.convertAST_toStringAST();
				if(isPrintAST){
					for(String string: stringAST){ 
						System.out.println(string);
					}
				}

				BuildAST astf =new  BuildAST();       // create abstract syntax tree factory
		        AST ast = astf. buildAbstractSyntaxTree(stringAST);  // get abstract syntax tree from astf using file data
		        
		        ast.standardize();
//		        System.out.println("############ STANDARD AST ###########");
		        if(isPrintST) ast.printAST();  // standardize ast
				
		        CSEMachineFactory csemfac = new CSEMachineFactory();  // create cse machine factory
		        CSEMachine csemachine = csemfac.getCSEMachine(ast);   // get cse machine with cse generated by ast
//		        csemachine.printControl();
//		        csemachine.printStack();
//		        csemachine.printEnvironment();
		       return csemachine.getAnswer();
			} catch (Exception e) {
				System.out.println(e.getMessage());
			}

        return null;

    

    }
}
